### ISSUE TITLE
добавь меня в дс пж

### ISSUE THREAD

**Issue by tretdm** [Pixelsuft/Pixelsuft#1]
если че, это Tinelix
`tretdm#9877`

**Comment by Pixelsuft** [comment]
лол, я ток щас увидел, сорян. если всё ещё что-то надо, то ответь, я добавлю

**Comment by tretdm** [comment]
> лол, я ток щас увидел, сорян. если всё ещё что-то надо, то ответь, я добавлю

уже по-новому добавляй - `tretdm`
